### PR TITLE
Problem: Signer `dylib` cannot spawn `async` tasks

### LINKED ISSUE #35: Problem: Signer `dylib` cannot spawn `async` tasks

### PR DESCRIPTION
**Pull request by devashishdxt**
Solution: Reverted the earlier change of passing `tokio::runtime::Handle` to `dylib`. To spawn `async` tasks, `dylib`s need to start their own runtime. Explained [here](https://github.com/crypto-com/ibc-solo-machine/issues/35#issuecomment-900748494). Fixes #35.

### CODE REVIEW

**Review by tomtau — APPROVED** [review]
👌

**Comment by tomtau** [comment]
FYI @linfeng-crypto may be looking into https://github.com/crypto-com/ibc-solo-machine/issues/3 so I guess good to start after this PR is merged?

**Comment by devashishdxt** [comment]
> FYI @linfeng-crypto may be looking into #3 so I guess good to start after this PR is merged?

Yes. The interface is (mostly) finalized and won't change unless we find any issues during end-to-end testing.

**Comment by jon-chuang** [comment]
Hey, I would really like to get tokio dy libs to work within a single executor. Any ideas on the workaround?

**Comment by devashishdxt** [comment]
> Hey, I would really like to get tokio dy libs to work within a single executor. Any ideas on the workaround?

I haven't found any workarounds for this as tokio uses thread local storage which is not shared between dynamic libraries.

**Comment by jon-chuang** [comment]
Note that this problem has now actually been solved by me: https://github.com/tokio-rs/tokio/pull/4493

**Pull request merged**
