### PR TITLE
Problem: `u32` for mint and burn amount may be small for ERC20 tokens

### LINKED ISSUE #49: Problem: `u32` for mint and burn amount may be small for ERC20 tokens
There is already an [issue](https://github.com/cosmos/ibc-go/issues/329) in `ibc-go` to add support for `BigInt` transfers. Right now, `ibc-go` supports `u64`. On solo machine, only `u32` is supported because there is no way to store `u64` values in SQLite and PostgreSQL using `sqlx`. Now that we don't maintain accounts and balances on solo machine, it'll be better to convert database type for amount to `TEXT` and convert `u32` to `u64` for mint and burn amounts.

### PR DESCRIPTION
**Pull request by devashishdxt**
Solution: Changed amount to `u64` and store it in database as `TEXT`. Fixes #49.

### CODE REVIEW

**Review by tomtau — COMMENTED** [review]
not a fan of storing numbers as TEXT, as it becomes a bit ambiguous and a bit wasteful (does it store digits, hex, base64... ? ) -- if it's just u64, then sqlite appears to have `UNSIGNED BIG INT` (or one could use BLOB and just store the byte array -- e.g. in low endian) and Postgres has `BIGSERIAL` or `NUMERIC` ?

**Comment by devashishdxt** [comment]
> not a fan of storing numbers as TEXT, as it becomes a bit ambiguous and a bit wasteful (does it store digits, hex, base64... ? ) -- if it's just u64, then sqlite appears to have `UNSIGNED BIG INT` (or one could use BLOB and just store the byte array -- e.g. in low endian) and Postgres has `BIGSERIAL` or `NUMERIC` ?

Database is not the limitation here, `sqlx` is (https://github.com/launchbadge/sqlx/issues/1374). SQLite and Postgres both (using `sqlx`) do not support storing `u64`.

**Comment by devashishdxt** [comment]
I'll try and store it in blob.

**Comment by tomtau** [comment]
ok -- if you go for BLOB because of sqlx, BYTEA may be a better fit in Postgres: https://www.postgresql.org/message-id/20150129142450.b83ce5d0652c39791292d0d5@potentialtech.com

**Comment by devashishdxt** [comment]
> ok -- if you go for BLOB because of sqlx, BYTEA may be a better fit in Postgres: https://www.postgresql.org/message-id/20150129142450.b83ce5d0652c39791292d0d5@potentialtech.com

Yes. I already use `BYTEA` for IBC data in postgres: https://github.com/crypto-com/ibc-solo-machine/blob/c47c54625caab7340c100851c9257c1a752a0d4f/solo-machine-core/postgres-migrations/20210629091441_ibc_data.up.sql#L3

**Review by jimmyyip-crypto — APPROVED** [review]
the proto schema looks good to me

**Review by tomtau — APPROVED** [review]

**Pull request merged**
