### PR TITLE
Problem: Solo machine does not support PostgreSQL

### LINKED ISSUE #34: Problem: Solo machine does not support PostgreSQL

### PR DESCRIPTION
**Pull request by devashishdxt**
Solution Added support for PostgreSQL. Fixes #34.

### CODE REVIEW

**Review by tomtau — COMMENTED** [review]
looks all right -- I guess the updated sql migrations should be compatible with both sqlite and Postgres?

**Comment by devashishdxt** [comment]
> looks all right -- I guess the updated sql migrations should be compatible with both sqlite and Postgres?

No. Now there are two folders: `sqlite-migrations` and `postgres-migrations` for each database. Some of the types in both are different so cannot use same migration files.

**Comment by tomtau** [comment]
ok, what is the reason for the updates in sqlite migrations? for the data types to better match what's in Postgres?

**Comment by devashishdxt** [comment]
> ok, what is the reason for the updates in sqlite migrations? for the data types to better match what's in Postgres?

Yes. There are no datatypes in postgres that can be converted to unsigned integers using sqlx. So, I had to use signed integers and change the data types in sqlite migrations.

**Comment by allthatjazzleo** [comment]
The solo-machine now support PostgreSQL, it becomes a stateless app itself connecting to RDS.
We can run on k8s instead of on a single machine.

**Review by tomtau — APPROVED** [review]

**Pull request merged**
