### PR TITLE
Problem: Dependencies are not upgraded to latest

### PR DESCRIPTION
**Pull request by devashishdxt**
Solution: Upgraded dependencies and fixed clippy warnings

### CODE REVIEW

**Review by tomtau — COMMENTED** [review]
do we have some integration test, or at least manual we can run?

**Comment by devashishdxt** [comment]
> do we have some integration test, or at least manual we can run?

Right now, no. But, I've assigned #16 to myself and will start working on this next.

**Review by tomtau — APPROVED** [review]
there are some strange dependencies in the tree, e.g.  parity-scale-codec, but I assume it's ok

**Comment by devashishdxt** [comment]
> those cargo audit issues are unrelated, still pending form #20 ?

It comes from `primitive-types` crate which we're using for `U256` type.

**Pull request merged**
