### PR TITLE
Problem: gRPC endpoints not supporting ibc-go 2.0.0

### LINKED ISSUE #78: Problem: gRPC endpoints not supporting ibc-go 2.0.0

### PR DESCRIPTION
**Pull request by devashishdxt**
Solution: Changed amounts in solo machine to `U256`. Fixes #78.

### CODE REVIEW

**Review by jimmyyip-crypto — APPROVED** [review]
LGTM
I just tested the original version with 3.3.0 chainmaind today and it worked without any code change (ofcoz only for small amount)
will test again tmr with this branch

**Comment by devashishdxt** [comment]
> LGTM I just tested the original version with 3.3.0 chainmaind today and it worked without any code change (ofcoz only for small amount) will test again tmr with this branch

@jimmyyip-crypto Can you also test with bigger amounts with this branch?

**Review by tomtau — APPROVED** [review]
utACK -- maybe the crate version / git tag can be increased after this is merged?

**Comment by jimmyyip-crypto** [comment]
> > LGTM I just tested the original version with 3.3.0 chainmaind today and it worked without any code change (ofcoz only for small amount) will test again tmr with this branch
> 
> @jimmyyip-crypto Can you also test with bigger amounts with this branch?

Tested in my local env. All good.

**Review by linfeng-crypto — APPROVED** [review]

**Pull request merged**
